import os
import json
import trimesh
from tqdm import tqdm
from multiprocessing import Pool

ARTIVERSE_PATH = "/cs/3dlg-jupiter-project/artiverse/singapo_data_full_filtered"



def process_model(args):
    category, model_id = args
    category_path = os.path.join(ARTIVERSE_PATH, category)
    model_path = os.path.join(category_path, model_id)

    if not os.path.isdir(model_path):
        return

    glbs_dir = os.path.join(model_path, "glbs")
    objs_dir = os.path.join(model_path, "textured_objs")

    if os.path.exists(objs_dir) or not os.path.exists(glbs_dir):
        return

    if not os.path.exists(os.path.join(model_path, "train_v3.json")):
        return

    os.makedirs(objs_dir, exist_ok=True)

    print(f" Converting model: {model_id}")

    for glb_file in os.listdir(glbs_dir):
        if not glb_file.endswith(".glb"):
            continue

        glb_path = os.path.join(glbs_dir, glb_file)
        obj_filename = glb_file.replace(".glb", ".obj").replace("part_", "original-")
        obj_path = os.path.join(objs_dir, obj_filename)

        # Load GLB
        glb_mesh = trimesh.load(glb_path)

        # Force unique MTL name
        mtl_name = obj_filename.replace(".obj", ".mtl")

        # Export OBJ
        glb_mesh.export(obj_path)

        # Rename autogenerated MTL
        auto_mtl_path = os.path.join(objs_dir, "material.mtl")
        if os.path.exists(auto_mtl_path):
            new_mtl_path = os.path.join(objs_dir, mtl_name)
            os.replace(auto_mtl_path, new_mtl_path)

        # Fix OBJ header
        if os.path.exists(obj_path):
            with open(obj_path, "r") as f:
                obj_text = f.read().replace("material.mtl", mtl_name)
            with open(obj_path, "w") as f:
                f.write(obj_text)


if __name__ == "__main__":
    for category in os.listdir(ARTIVERSE_PATH):
        category_path = os.path.join(ARTIVERSE_PATH, category)
        if not os.path.isdir(category_path):
            continue

        print(f"Processing category: {category}")

        models = [m for m in os.listdir(category_path)
                  if os.path.isdir(os.path.join(category_path, m))]

        with Pool() as pool:
            list(tqdm(pool.imap_unordered(process_model,
                                          [(category, m) for m in models]),
                      total=len(models)))

