mode: online # (online, offline). Offline uses more memory
checkpoint_path: "/local-scratch/localhome/efa33/projects/articulate-anything/cotracker2.pth"
grid_size: 30
render_all: false
displacement_threshold: null
max_moving_points: null
linewidth: 5
overwrite: true